### ISSUE TITLE
Header 高度和 ant.design 保持一致

### ISSUE THREAD

**Issue by afc163** [ant-motion/ant-motion#2]

**Comment by hi-caicai** [comment]
🐶

**Comment by jljsj33** [comment]
@afc163 你不觉得 ant-d 的 header 太高了？ 跟青口商量下把高改成64。。。。

**Comment by Chinglik** [comment]
你们师徒俩为什么把 AntDesign 的 logo 改得那么小，Ant Motion 又那么大。合适么？
ps.我居然也可以在 github 跟大家谈笑风生

**Comment by jljsj33** [comment]
@Chinglik 哈哈，，就是 ant-d 的太高了所以视觉上感觉 logo 变小了。。其它一样大。。。logo 图片高为33， ant-d 的字是太小了。。。

**Comment by jljsj33** [comment]
一个码农提了个issues, 三个设计师在下面喊。。。。
