### ISSUE TITLE
rc-queue-anim 报错: Uncaught Invariant Violation

### ISSUE THREAD

**Issue by weiq** [ant-motion/ant-motion#6]
使用例子中的代码：

```
import React from 'react';
import ReactDOM from 'react-dom';

import QueueAnim from 'rc-queue-anim';
ReactDOM.render(<QueueAnim>
  <div key="demo1">依次进场</div>
  <div key="demo2">依次进场</div>
  <div key="demo3">依次进场</div>
  <div key="demo4">依次进场</div>
</QueueAnim>, document.getElementById('root'));
```
控制台报错：

invariant.js:39  ：

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

环境
···
    "antd": "^1.1.0",
    "atool-build": "0.6.x",
    "babel-plugin-antd": "0.3.x",
    "chart.js": "^1.1.1",
    "es3ify-loader": "^0.1.0",
    "history": "^2.1.1",
    "lodash": "^4.13.1",
    "rc-queue-anim": "^0.11.9",
    "react": "0.14.x",
    "react-chartjs": "^0.7.3",
    "react-dom": "0.14.x",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.0",
    "react-router-redux": "^4.0.4",
    "redux": "^3.5.2",
    "redux-thunk": "^2.0.1",
    "superagent": "^1.8.3"
···

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001
