### ISSUE TITLE
need to test other animation components for same issue

### ISSUE THREAD

**Issue by plandem** [ant-motion/ant-motion#8]
https://github.com/ant-design/ant-design/issues/2040

**Comment by jljsj33** [comment]
have demo?

**Comment by plandem** [comment]
only real application :(

the case is:
1) i have page that secure (after login)
2) i click logout (it's dropdown with menu as overlay)
3) after that i redirect to page that totally new - totally different layout - login page.
4) we had exception because didUnmount tries to use child that already null


the main idea - just check for **child != null**  before using **child.key** at unmounting phase

**Comment by jljsj33** [comment]
ok, thanks
